kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-configmaps-binding
  namespace: demo-multicloud
subjects:
  - kind: ServiceAccount
    name: default
    namespace: demo-multicloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmap-reader-role
