kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configmap-reader-role
  namespace: demo-facturacion
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps