kind: Console
apiVersion: console.streamshub.github.com/v1alpha1
metadata:
  name: demo
  namespace: kafka-console
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  hostname: demo-kafka-console.apps.cluster-stb2g.dynamic.redhatworkshops.io
  kafkaClusters:
    - listener: plain
      name: demo-cluster
      namespace: demo-multicloud
