apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: demo
  namespace: kafka-console
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  hostname: demo-kafka-console.apps.cluster-9v7mx.9v7mx.gcp.redhatworkshops.io
  kafkaClusters:
    - listener: plain
      name: demo-cluster
      namespace: demo-multicloud