quarkus.devservices.enabled=true
quarkus.devservices.kafka.enabled=true
quarkus.kafka.devservices.shared=true
quarkus.kafka.devservices.port=9092
quarkus.kafka.devservices.provider=strimzi

quarkus.native.container-build=true
quarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:jdk-21.0.2-amd64
quarkus.native.container-runtime=podman

%dev.kafka.topic=my-topic

%dev.body.message = Mensaje generado en
%dev.kafka.brokers=localhost:9092

%prod.quarkus.devservices.enabled=false
%prod.quarkus.devservices.kafka.enabled=false
%prod.quarkus.kubernetes-config.enabled=true
%prod.quarkus.kubernetes-config.config-maps=kafka-config
#%prod.body.message = Mensaje generado en ambiente de producción
#%prod.kafka.brokers=demo-cluster-kafka-bootstrap:9092
%prod.kafka.brokers= ${kafka-bootstrap}
%prod.body.message = ${kafka-message}
%prod.kafka.topic = ${kafka-topic}

# Enable the jolokia java-agent on the quarkus application
quarkus.openshift.env.vars.JAVA_OPTS_APPEND=-javaagent:lib/main/org.jolokia.jolokia-agent-jvm-${jolokia-version}-javaagent.jar=protocol=${jolokia.protocol}\,host=${jolokia.host}\,port=${jolokia.port}\,useSslClientAuthentication=${jolokia.useSslClientAuthentication}\,caCert=${jolokia.caCert}\,clientPrincipal.1=${jolokia.clientPrincipal.1}\,extendedClientCheck=${jolokia.extendedClientCheck}\,discoveryEnabled=${jolokia.discoveryEnabled}
# Define the Jolokia port on the container for HawtIO access
quarkus.openshift.ports.jolokia.container-port=${jolokia.port}
quarkus.openshift.ports.jolokia.protocol=TCP
#-javaagent:lib/main/org.jolokia.jolokia-agent-jvm-2.5.1-javaagent.jar=protocol=https\,host=*\,port=8778\,useSslClientAuthentication=true\,caCert=/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt\,clientPrincipal.1=cn=hawtio-online.hawtio.svc\,extendedClientCheck=true\,discoveryEnabled=false