quarkus.devservices.enabled=true
quarkus.devservices.kafka.enabled=true
quarkus.kafka.devservices.shared=true
quarkus.kafka.devservices.port=9092
quarkus.kafka.devservices.provider=strimzi

quarkus.native.container-build=true
quarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:jdk-21.0.2-amd64
quarkus.native.container-runtime=podman

%dev.kafka.topic=my-topic

%dev.body.message = Mensaje generado en
%dev.kafka.brokers=localhost:9092

%prod.quarkus.devservices.enabled=false
%prod.quarkus.devservices.kafka.enabled=false
%prod.quarkus.kubernetes-config.enabled=true
%prod.quarkus.kubernetes-config.config-maps=kafka-config
#%prod.body.message = Mensaje generado en ambiente de producción
#%prod.kafka.brokers=demo-cluster-kafka-bootstrap:9092
%prod.kafka.brokers= ${kafka-bootstrap}
%prod.body.message = ${kafka-message}
%prod.kafka.topic = ${kafka-topic}