apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: hybrid
  labels:
    strimzi.io/cluster: demo-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared